### ISSUE TITLE
plugin code for flake8-copyright does not match regex

### ISSUE THREAD

**Issue by duboise-cnes** [savoirfairelinux/flake8-copyright#18]
Hello, 

for information, the plugin is no usable anymore through last flake8 version.
Seems that flake8 have constrained the plugin code possibilities through a regex. 
We are going to desactivate flake8-copyright in our software. 

```
Linting flake8 check
There was a critical error during execution of Flake8:
plugin code for `flake8-copyright[flake8_copyright]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

Interested if this bug is resolved
Cordially, 
Emmanuel

**Comment by The-Compiler** [comment]
See #9 - unfortunately, this project seems pretty much dead at this point...

**Comment by duboise-cnes** [comment]
Thanks for the quick answer and the project status. I am erasing the dependency of our project for now. A pity because this plugin was really helpful.

**Comment by The-Compiler** [comment]
I agree! Note that I'm not a maintainer or anything - but given that a PR fixing this has been open for years, I don't count on it happening anymore...

**Comment by televi** [comment]
I have a fork with a fix for this but I have no way to merge it here or release it.  I'm tempted to create a new project (flake8-copyright2 or something) and release the fix there (and nuke support for old, unsupported pythons and update to use modern build tools and add stuff to actually build wheels and ...). 

In the mean time, feel free to use my fork if you'd like.  To build it,
```
python3.8 -m venv env
source env/bin/activate
pip install setuptools wheel
python setup.py bdist_wheel
```
At that point, you should have a wheel file sitting in the dist directory that you can pip install.  I bumped the version to 0.2.3 so it won't collide with the existing plugin.

If you want to change the code yourself, it's actually very simple - just look at the entry point in setup.py.  That's the only change needed for this to work.

**Comment by duboise-cnes** [comment]
Hello, thanks for the answer. I cannot see your fork and modifications : is there a github repo link ? 

Anyway, I will use a project if maintained now : If you do a new project for an improved flake8-copyright please say so. I would be happy to test and help maintaining it (to be able to improve it if dependencies and flake8 paradigms evolves...) 
Otherwise, the plugin is not mandatory for our developement, I prefer now waiting for a more maintained plugin with many people using and modifying it.

**Comment by televi** [comment]
The link to the fork is here: https://github.com/televi/flake8-copyright  - it's listed as public so anyone should be able to see it 😄

**Comment by televi** [comment]
I sent email to the owner's email address asking if they have time to accept a PR or, if they simply don't have time to support this project, if they'd mind transfering it to me so I can fix it and push a new release.  I'll update here based on my response.  FYI, the email address was for a support account for Savoir-Faire Linux - it issued a ticket to my email so I'm hopeful someone will get back to me.

**Comment by mrodriguezg1991** [comment]
Hello, a new version 0.2.3 was release with the update from this PR.
Let us know if this issue is solve

**Comment by televi** [comment]
Just to close this out, the support folks did get back to me and fixed the issue.  The response I got also said they would talk to their other developers about picking this up more formally going foward, so all very good news 😄

**Comment by The-Compiler** [comment]
Thanks @televi, @mrodriguezg1991 and @dopplershift! This seems indeed to be working fine now.
